//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Accelerator.EBS.SharedServices.ProxyClasses.OrdersByContact {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OE_ORDER_CUST_Binding", Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/")]
    public partial class OE_ORDER_CUST_Service : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private SOAHeader sOAHeaderValueField;
        
        private System.Threading.SendOrPostCallback GET_ORDERS_BY_CONTACTOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_ORDERS_BY_INCIDENTOperationCompleted;
        
        /// <remarks/>
        public OE_ORDER_CUST_Service() {
            this.Url = "http://ebs.example.com:8000/webservices/SOAProvider/plsql/oe_order_cust/";
        }
        
        public SOAHeader SOAHeaderValue {
            get {
                return this.sOAHeaderValueField;
            }
            set {
                this.sOAHeaderValueField = value;
            }
        }
        
        /// <remarks/>
        public event GET_ORDERS_BY_CONTACTCompletedEventHandler GET_ORDERS_BY_CONTACTCompleted;
        
        /// <remarks/>
        public event GET_ORDERS_BY_INCIDENTCompletedEventHandler GET_ORDERS_BY_INCIDENTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ebs.example.com:8000/webservices/SOAProvider/plsql/oe_order_cust/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_co" +
            "ntact/")]
        public OutputParameters GET_ORDERS_BY_CONTACT([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_co" +
            "ntact/")] InputParameters InputParameters) {
            object[] results = this.Invoke("GET_ORDERS_BY_CONTACT", new object[] {
                        InputParameters});
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGET_ORDERS_BY_CONTACT(InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GET_ORDERS_BY_CONTACT", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters EndGET_ORDERS_BY_CONTACT(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public void GET_ORDERS_BY_CONTACTAsync(InputParameters InputParameters) {
            this.GET_ORDERS_BY_CONTACTAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void GET_ORDERS_BY_CONTACTAsync(InputParameters InputParameters, object userState) {
            if ((this.GET_ORDERS_BY_CONTACTOperationCompleted == null)) {
                this.GET_ORDERS_BY_CONTACTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_ORDERS_BY_CONTACTOperationCompleted);
            }
            this.InvokeAsync("GET_ORDERS_BY_CONTACT", new object[] {
                        InputParameters}, this.GET_ORDERS_BY_CONTACTOperationCompleted, userState);
        }
        
        private void OnGET_ORDERS_BY_CONTACTOperationCompleted(object arg) {
            if ((this.GET_ORDERS_BY_CONTACTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_ORDERS_BY_CONTACTCompleted(this, new GET_ORDERS_BY_CONTACTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ebs.example.com:8000/webservices/SOAProvider/plsql/oe_order_cust/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_in" +
            "cident/")]
        public OutputParameters1 GET_ORDERS_BY_INCIDENT([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_in" +
            "cident/")] InputParameters1 InputParameters) {
            object[] results = this.Invoke("GET_ORDERS_BY_INCIDENT", new object[] {
                        InputParameters});
            return ((OutputParameters1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGET_ORDERS_BY_INCIDENT(InputParameters1 InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GET_ORDERS_BY_INCIDENT", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters1 EndGET_ORDERS_BY_INCIDENT(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters1)(results[0]));
        }
        
        /// <remarks/>
        public void GET_ORDERS_BY_INCIDENTAsync(InputParameters1 InputParameters) {
            this.GET_ORDERS_BY_INCIDENTAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void GET_ORDERS_BY_INCIDENTAsync(InputParameters1 InputParameters, object userState) {
            if ((this.GET_ORDERS_BY_INCIDENTOperationCompleted == null)) {
                this.GET_ORDERS_BY_INCIDENTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_ORDERS_BY_INCIDENTOperationCompleted);
            }
            this.InvokeAsync("GET_ORDERS_BY_INCIDENT", new object[] {
                        InputParameters}, this.GET_ORDERS_BY_INCIDENTOperationCompleted, userState);
        }
        
        private void OnGET_ORDERS_BY_INCIDENTOperationCompleted(object arg) {
            if ((this.GET_ORDERS_BY_INCIDENTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_ORDERS_BY_INCIDENTCompleted(this, new GET_ORDERS_BY_INCIDENTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/", IsNullable=false)]
    public partial class SOAHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string responsibilityField;
        
        private string respApplicationField;
        
        private string securityGroupField;
        
        private string nLSLanguageField;
        
        private string org_IdField;
        
        /// <remarks/>
        public string Responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
            }
        }
        
        /// <remarks/>
        public string RespApplication {
            get {
                return this.respApplicationField;
            }
            set {
                this.respApplicationField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityGroup {
            get {
                return this.securityGroupField;
            }
            set {
                this.securityGroupField = value;
            }
        }
        
        /// <remarks/>
        public string NLSLanguage {
            get {
                return this.nLSLanguageField;
            }
            set {
                this.nLSLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.OE_ORDER_CUST_ORX3349377X2X3", Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_in" +
        "cident/")]
    public partial class APPSOE_ORDER_CUST_ORX3349377X2X3 {
        
        private System.Nullable<decimal> hEADER_IDField;
        
        private bool hEADER_IDFieldSpecified;
        
        private System.Nullable<decimal> sOLD_TO_CONTACT_IDField;
        
        private bool sOLD_TO_CONTACT_IDFieldSpecified;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private System.Nullable<System.DateTime> lAST_UPDATE_DATEField;
        
        private bool lAST_UPDATE_DATEFieldSpecified;
        
        private System.Nullable<decimal> oRDER_NUMBERField;
        
        private bool oRDER_NUMBERFieldSpecified;
        
        private string fLOW_STATUS_CODEField;
        
        private string oRDER_CATEGORY_CODEField;
        
        private System.Nullable<decimal> oRDER_TYPE_IDField;
        
        private bool oRDER_TYPE_IDFieldSpecified;
        
        private string oRIG_SYS_DOCUMENT_REFField;
        
        private string tRANSACTIONAL_CURR_CODEField;
        
        private string cANCELLED_FLAGField;
        
        private string oPEN_FLAGField;
        
        private string bOOKED_FLAGField;
        
        private System.Nullable<decimal> vERSION_NUMBERField;
        
        private bool vERSION_NUMBERFieldSpecified;
        
        private string aTTRIBUTE15Field;
        
        private string aTTRIBUTE16Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> HEADER_ID {
            get {
                return this.hEADER_IDField;
            }
            set {
                this.hEADER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HEADER_IDSpecified {
            get {
                return this.hEADER_IDFieldSpecified;
            }
            set {
                this.hEADER_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SOLD_TO_CONTACT_ID {
            get {
                return this.sOLD_TO_CONTACT_IDField;
            }
            set {
                this.sOLD_TO_CONTACT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SOLD_TO_CONTACT_IDSpecified {
            get {
                return this.sOLD_TO_CONTACT_IDFieldSpecified;
            }
            set {
                this.sOLD_TO_CONTACT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LAST_UPDATE_DATE {
            get {
                return this.lAST_UPDATE_DATEField;
            }
            set {
                this.lAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATE_DATESpecified {
            get {
                return this.lAST_UPDATE_DATEFieldSpecified;
            }
            set {
                this.lAST_UPDATE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORDER_NUMBER {
            get {
                return this.oRDER_NUMBERField;
            }
            set {
                this.oRDER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORDER_NUMBERSpecified {
            get {
                return this.oRDER_NUMBERFieldSpecified;
            }
            set {
                this.oRDER_NUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FLOW_STATUS_CODE {
            get {
                return this.fLOW_STATUS_CODEField;
            }
            set {
                this.fLOW_STATUS_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORDER_CATEGORY_CODE {
            get {
                return this.oRDER_CATEGORY_CODEField;
            }
            set {
                this.oRDER_CATEGORY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORDER_TYPE_ID {
            get {
                return this.oRDER_TYPE_IDField;
            }
            set {
                this.oRDER_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORDER_TYPE_IDSpecified {
            get {
                return this.oRDER_TYPE_IDFieldSpecified;
            }
            set {
                this.oRDER_TYPE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORIG_SYS_DOCUMENT_REF {
            get {
                return this.oRIG_SYS_DOCUMENT_REFField;
            }
            set {
                this.oRIG_SYS_DOCUMENT_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRANSACTIONAL_CURR_CODE {
            get {
                return this.tRANSACTIONAL_CURR_CODEField;
            }
            set {
                this.tRANSACTIONAL_CURR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CANCELLED_FLAG {
            get {
                return this.cANCELLED_FLAGField;
            }
            set {
                this.cANCELLED_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OPEN_FLAG {
            get {
                return this.oPEN_FLAGField;
            }
            set {
                this.oPEN_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BOOKED_FLAG {
            get {
                return this.bOOKED_FLAGField;
            }
            set {
                this.bOOKED_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> VERSION_NUMBER {
            get {
                return this.vERSION_NUMBERField;
            }
            set {
                this.vERSION_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VERSION_NUMBERSpecified {
            get {
                return this.vERSION_NUMBERFieldSpecified;
            }
            set {
                this.vERSION_NUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ATTRIBUTE15 {
            get {
                return this.aTTRIBUTE15Field;
            }
            set {
                this.aTTRIBUTE15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ATTRIBUTE16 {
            get {
                return this.aTTRIBUTE16Field;
            }
            set {
                this.aTTRIBUTE16Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.OE_ORDER_CUST_ORX3349377X1X3", Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_co" +
        "ntact/")]
    public partial class APPSOE_ORDER_CUST_ORX3349377X1X3 {
        
        private System.Nullable<decimal> hEADER_IDField;
        
        private bool hEADER_IDFieldSpecified;
        
        private System.Nullable<decimal> sOLD_TO_CONTACT_IDField;
        
        private bool sOLD_TO_CONTACT_IDFieldSpecified;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private System.Nullable<System.DateTime> lAST_UPDATE_DATEField;
        
        private bool lAST_UPDATE_DATEFieldSpecified;
        
        private System.Nullable<decimal> oRDER_NUMBERField;
        
        private bool oRDER_NUMBERFieldSpecified;
        
        private string fLOW_STATUS_CODEField;
        
        private string oRDER_CATEGORY_CODEField;
        
        private System.Nullable<decimal> oRDER_TYPE_IDField;
        
        private bool oRDER_TYPE_IDFieldSpecified;
        
        private string oRIG_SYS_DOCUMENT_REFField;
        
        private string tRANSACTIONAL_CURR_CODEField;
        
        private string cANCELLED_FLAGField;
        
        private string oPEN_FLAGField;
        
        private string bOOKED_FLAGField;
        
        private System.Nullable<decimal> vERSION_NUMBERField;
        
        private bool vERSION_NUMBERFieldSpecified;
        
        private string aTTRIBUTE15Field;
        
        private string aTTRIBUTE16Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> HEADER_ID {
            get {
                return this.hEADER_IDField;
            }
            set {
                this.hEADER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HEADER_IDSpecified {
            get {
                return this.hEADER_IDFieldSpecified;
            }
            set {
                this.hEADER_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SOLD_TO_CONTACT_ID {
            get {
                return this.sOLD_TO_CONTACT_IDField;
            }
            set {
                this.sOLD_TO_CONTACT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SOLD_TO_CONTACT_IDSpecified {
            get {
                return this.sOLD_TO_CONTACT_IDFieldSpecified;
            }
            set {
                this.sOLD_TO_CONTACT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LAST_UPDATE_DATE {
            get {
                return this.lAST_UPDATE_DATEField;
            }
            set {
                this.lAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATE_DATESpecified {
            get {
                return this.lAST_UPDATE_DATEFieldSpecified;
            }
            set {
                this.lAST_UPDATE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORDER_NUMBER {
            get {
                return this.oRDER_NUMBERField;
            }
            set {
                this.oRDER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORDER_NUMBERSpecified {
            get {
                return this.oRDER_NUMBERFieldSpecified;
            }
            set {
                this.oRDER_NUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FLOW_STATUS_CODE {
            get {
                return this.fLOW_STATUS_CODEField;
            }
            set {
                this.fLOW_STATUS_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORDER_CATEGORY_CODE {
            get {
                return this.oRDER_CATEGORY_CODEField;
            }
            set {
                this.oRDER_CATEGORY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORDER_TYPE_ID {
            get {
                return this.oRDER_TYPE_IDField;
            }
            set {
                this.oRDER_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORDER_TYPE_IDSpecified {
            get {
                return this.oRDER_TYPE_IDFieldSpecified;
            }
            set {
                this.oRDER_TYPE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORIG_SYS_DOCUMENT_REF {
            get {
                return this.oRIG_SYS_DOCUMENT_REFField;
            }
            set {
                this.oRIG_SYS_DOCUMENT_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRANSACTIONAL_CURR_CODE {
            get {
                return this.tRANSACTIONAL_CURR_CODEField;
            }
            set {
                this.tRANSACTIONAL_CURR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CANCELLED_FLAG {
            get {
                return this.cANCELLED_FLAGField;
            }
            set {
                this.cANCELLED_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OPEN_FLAG {
            get {
                return this.oPEN_FLAGField;
            }
            set {
                this.oPEN_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BOOKED_FLAG {
            get {
                return this.bOOKED_FLAGField;
            }
            set {
                this.bOOKED_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> VERSION_NUMBER {
            get {
                return this.vERSION_NUMBERField;
            }
            set {
                this.vERSION_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VERSION_NUMBERSpecified {
            get {
                return this.vERSION_NUMBERFieldSpecified;
            }
            set {
                this.vERSION_NUMBERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ATTRIBUTE15 {
            get {
                return this.aTTRIBUTE15Field;
            }
            set {
                this.aTTRIBUTE15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ATTRIBUTE16 {
            get {
                return this.aTTRIBUTE16Field;
            }
            set {
                this.aTTRIBUTE16Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_co" +
        "ntact/")]
    public partial class InputParameters {
        
        private System.Nullable<decimal> p_CONTACT_PARTY_IDField;
        
        private bool p_CONTACT_PARTY_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_CONTACT_PARTY_ID {
            get {
                return this.p_CONTACT_PARTY_IDField;
            }
            set {
                this.p_CONTACT_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_CONTACT_PARTY_IDSpecified {
            get {
                return this.p_CONTACT_PARTY_IDFieldSpecified;
            }
            set {
                this.p_CONTACT_PARTY_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_co" +
        "ntact/")]
    public partial class OutputParameters {
        
        private APPSOE_ORDER_CUST_ORX3349377X1X3[] x_ORDERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("X_ORDERS_ITEM")]
        public APPSOE_ORDER_CUST_ORX3349377X1X3[] X_ORDERS {
            get {
                return this.x_ORDERSField;
            }
            set {
                this.x_ORDERSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_in" +
        "cident/")]
    public partial class InputParameters1 {
        
        private string p_INCIDENT_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_INCIDENT_NUMBER {
            get {
                return this.p_INCIDENT_NUMBERField;
            }
            set {
                this.p_INCIDENT_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/ont/soaprovider/plsql/oe_order_cust/get_orders_by_in" +
        "cident/")]
    public partial class OutputParameters1 {
        
        private APPSOE_ORDER_CUST_ORX3349377X2X3[] x_ORDERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("X_ORDERS_ITEM")]
        public APPSOE_ORDER_CUST_ORX3349377X2X3[] X_ORDERS {
            get {
                return this.x_ORDERSField;
            }
            set {
                this.x_ORDERSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GET_ORDERS_BY_CONTACTCompletedEventHandler(object sender, GET_ORDERS_BY_CONTACTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_ORDERS_BY_CONTACTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_ORDERS_BY_CONTACTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GET_ORDERS_BY_INCIDENTCompletedEventHandler(object sender, GET_ORDERS_BY_INCIDENTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_ORDERS_BY_INCIDENTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_ORDERS_BY_INCIDENTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters1)(this.results[0]));
            }
        }
    }
}
