//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Accelerator.EBS.SharedServices.ProxyClasses.ServiceRequest.Lookup {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CS_SERVICEREQUEST_CUST_Binding", Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/")]
    public partial class CS_SERVICEREQUEST_CUST_Service : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private SOAHeader sOAHeaderValueField;
        
        private System.Threading.SendOrPostCallback GET_SERVICE_REQUEST_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback GET_SERVICE_REQUEST_LISTOperationCompleted;
        
        /// <remarks/>
        public CS_SERVICEREQUEST_CUST_Service() {
            this.Url = "http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/cs_servicerequ" +
                "est_cust/";
        }
        
        public SOAHeader SOAHeaderValue {
            get {
                return this.sOAHeaderValueField;
            }
            set {
                this.sOAHeaderValueField = value;
            }
        }
        
        /// <remarks/>
        public event GET_SERVICE_REQUEST_INFOCompletedEventHandler GET_SERVICE_REQUEST_INFOCompleted;
        
        /// <remarks/>
        public event GET_SERVICE_REQUEST_LISTCompletedEventHandler GET_SERVICE_REQUEST_LISTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/cs_servicerequ" +
            "est_cust/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
            "vice_request_info/")]
        public OutputParameters GET_SERVICE_REQUEST_INFO([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
            "vice_request_info/")] InputParameters InputParameters) {
            object[] results = this.Invoke("GET_SERVICE_REQUEST_INFO", new object[] {
                        InputParameters});
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGET_SERVICE_REQUEST_INFO(InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GET_SERVICE_REQUEST_INFO", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters EndGET_SERVICE_REQUEST_INFO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public void GET_SERVICE_REQUEST_INFOAsync(InputParameters InputParameters) {
            this.GET_SERVICE_REQUEST_INFOAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void GET_SERVICE_REQUEST_INFOAsync(InputParameters InputParameters, object userState) {
            if ((this.GET_SERVICE_REQUEST_INFOOperationCompleted == null)) {
                this.GET_SERVICE_REQUEST_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_SERVICE_REQUEST_INFOOperationCompleted);
            }
            this.InvokeAsync("GET_SERVICE_REQUEST_INFO", new object[] {
                        InputParameters}, this.GET_SERVICE_REQUEST_INFOOperationCompleted, userState);
        }
        
        private void OnGET_SERVICE_REQUEST_INFOOperationCompleted(object arg) {
            if ((this.GET_SERVICE_REQUEST_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_SERVICE_REQUEST_INFOCompleted(this, new GET_SERVICE_REQUEST_INFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/cs_servicerequ" +
            "est_cust/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
            "vice_request_list/")]
        public OutputParameters1 GET_SERVICE_REQUEST_LIST([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
            "vice_request_list/")] InputParameters1 InputParameters) {
            object[] results = this.Invoke("GET_SERVICE_REQUEST_LIST", new object[] {
                        InputParameters});
            return ((OutputParameters1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGET_SERVICE_REQUEST_LIST(InputParameters1 InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GET_SERVICE_REQUEST_LIST", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters1 EndGET_SERVICE_REQUEST_LIST(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters1)(results[0]));
        }
        
        /// <remarks/>
        public void GET_SERVICE_REQUEST_LISTAsync(InputParameters1 InputParameters) {
            this.GET_SERVICE_REQUEST_LISTAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void GET_SERVICE_REQUEST_LISTAsync(InputParameters1 InputParameters, object userState) {
            if ((this.GET_SERVICE_REQUEST_LISTOperationCompleted == null)) {
                this.GET_SERVICE_REQUEST_LISTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_SERVICE_REQUEST_LISTOperationCompleted);
            }
            this.InvokeAsync("GET_SERVICE_REQUEST_LIST", new object[] {
                        InputParameters}, this.GET_SERVICE_REQUEST_LISTOperationCompleted, userState);
        }
        
        private void OnGET_SERVICE_REQUEST_LISTOperationCompleted(object arg) {
            if ((this.GET_SERVICE_REQUEST_LISTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_SERVICE_REQUEST_LISTCompleted(this, new GET_SERVICE_REQUEST_LISTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/", IsNullable=false)]
    public partial class SOAHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string responsibilityField;
        
        private string respApplicationField;
        
        private string securityGroupField;
        
        private string nLSLanguageField;
        
        private string org_IdField;
        
        /// <remarks/>
        public string Responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
            }
        }
        
        /// <remarks/>
        public string RespApplication {
            get {
                return this.respApplicationField;
            }
            set {
                this.respApplicationField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityGroup {
            get {
                return this.securityGroupField;
            }
            set {
                this.securityGroupField = value;
            }
        }
        
        /// <remarks/>
        public string NLSLanguage {
            get {
                return this.nLSLanguageField;
            }
            set {
                this.nLSLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CS_SERVICEREQUEX16438971X2X3", Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
        "vice_request_list/")]
    public partial class APPSCS_SERVICEREQUEX16438971X2X3 {
        
        private string iNCIDENT_NUMBERField;
        
        private System.Nullable<decimal> iNCIDENT_IDField;
        
        private bool iNCIDENT_IDFieldSpecified;
        
        private string iNCIDENT_SUMMARYField;
        
        private string iNCIDENT_TYPEField;
        
        private System.Nullable<decimal> iNCIDENT_TYPE_IDField;
        
        private bool iNCIDENT_TYPE_IDFieldSpecified;
        
        private string iNCIDENT_STATUSField;
        
        private System.Nullable<decimal> iNCIDENT_STATUS_IDField;
        
        private bool iNCIDENT_STATUS_IDFieldSpecified;
        
        private string iNCIDENT_SEVERITYField;
        
        private System.Nullable<decimal> iNCIDENT_SEVERITY_IDField;
        
        private bool iNCIDENT_SEVERITY_IDFieldSpecified;
        
        private string iNCIDENT_ATTRIBUTE_14Field;
        
        private string iNCIDENT_ATTRIBUTE_15Field;
        
        private System.Nullable<decimal> cONTACT_PARTY_IDField;
        
        private bool cONTACT_PARTY_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_NUMBER {
            get {
                return this.iNCIDENT_NUMBERField;
            }
            set {
                this.iNCIDENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_ID {
            get {
                return this.iNCIDENT_IDField;
            }
            set {
                this.iNCIDENT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_IDSpecified {
            get {
                return this.iNCIDENT_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_SUMMARY {
            get {
                return this.iNCIDENT_SUMMARYField;
            }
            set {
                this.iNCIDENT_SUMMARYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_TYPE {
            get {
                return this.iNCIDENT_TYPEField;
            }
            set {
                this.iNCIDENT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_TYPE_ID {
            get {
                return this.iNCIDENT_TYPE_IDField;
            }
            set {
                this.iNCIDENT_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_TYPE_IDSpecified {
            get {
                return this.iNCIDENT_TYPE_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_TYPE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_STATUS {
            get {
                return this.iNCIDENT_STATUSField;
            }
            set {
                this.iNCIDENT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_STATUS_ID {
            get {
                return this.iNCIDENT_STATUS_IDField;
            }
            set {
                this.iNCIDENT_STATUS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_STATUS_IDSpecified {
            get {
                return this.iNCIDENT_STATUS_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_STATUS_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_SEVERITY {
            get {
                return this.iNCIDENT_SEVERITYField;
            }
            set {
                this.iNCIDENT_SEVERITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_SEVERITY_ID {
            get {
                return this.iNCIDENT_SEVERITY_IDField;
            }
            set {
                this.iNCIDENT_SEVERITY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_SEVERITY_IDSpecified {
            get {
                return this.iNCIDENT_SEVERITY_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_SEVERITY_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_ATTRIBUTE_14 {
            get {
                return this.iNCIDENT_ATTRIBUTE_14Field;
            }
            set {
                this.iNCIDENT_ATTRIBUTE_14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_ATTRIBUTE_15 {
            get {
                return this.iNCIDENT_ATTRIBUTE_15Field;
            }
            set {
                this.iNCIDENT_ATTRIBUTE_15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CONTACT_PARTY_ID {
            get {
                return this.cONTACT_PARTY_IDField;
            }
            set {
                this.cONTACT_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CONTACT_PARTY_IDSpecified {
            get {
                return this.cONTACT_PARTY_IDFieldSpecified;
            }
            set {
                this.cONTACT_PARTY_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CS_SERVICEREQUEX16438971X1X2", Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
        "vice_request_info/")]
    public partial class APPSCS_SERVICEREQUEX16438971X1X2 {
        
        private string iNCIDENT_NUMBERField;
        
        private System.Nullable<decimal> iNCIDENT_IDField;
        
        private bool iNCIDENT_IDFieldSpecified;
        
        private string iNCIDENT_SUMMARYField;
        
        private string iNCIDENT_TYPEField;
        
        private System.Nullable<decimal> iNCIDENT_TYPE_IDField;
        
        private bool iNCIDENT_TYPE_IDFieldSpecified;
        
        private string iNCIDENT_STATUSField;
        
        private System.Nullable<decimal> iNCIDENT_STATUS_IDField;
        
        private bool iNCIDENT_STATUS_IDFieldSpecified;
        
        private string iNCIDENT_SEVERITYField;
        
        private System.Nullable<decimal> iNCIDENT_SEVERITY_IDField;
        
        private bool iNCIDENT_SEVERITY_IDFieldSpecified;
        
        private string iNCIDENT_ATTRIBUTE_14Field;
        
        private string iNCIDENT_ATTRIBUTE_15Field;
        
        private System.Nullable<decimal> cONTACT_PARTY_IDField;
        
        private bool cONTACT_PARTY_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_NUMBER {
            get {
                return this.iNCIDENT_NUMBERField;
            }
            set {
                this.iNCIDENT_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_ID {
            get {
                return this.iNCIDENT_IDField;
            }
            set {
                this.iNCIDENT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_IDSpecified {
            get {
                return this.iNCIDENT_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_SUMMARY {
            get {
                return this.iNCIDENT_SUMMARYField;
            }
            set {
                this.iNCIDENT_SUMMARYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_TYPE {
            get {
                return this.iNCIDENT_TYPEField;
            }
            set {
                this.iNCIDENT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_TYPE_ID {
            get {
                return this.iNCIDENT_TYPE_IDField;
            }
            set {
                this.iNCIDENT_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_TYPE_IDSpecified {
            get {
                return this.iNCIDENT_TYPE_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_TYPE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_STATUS {
            get {
                return this.iNCIDENT_STATUSField;
            }
            set {
                this.iNCIDENT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_STATUS_ID {
            get {
                return this.iNCIDENT_STATUS_IDField;
            }
            set {
                this.iNCIDENT_STATUS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_STATUS_IDSpecified {
            get {
                return this.iNCIDENT_STATUS_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_STATUS_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_SEVERITY {
            get {
                return this.iNCIDENT_SEVERITYField;
            }
            set {
                this.iNCIDENT_SEVERITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> INCIDENT_SEVERITY_ID {
            get {
                return this.iNCIDENT_SEVERITY_IDField;
            }
            set {
                this.iNCIDENT_SEVERITY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INCIDENT_SEVERITY_IDSpecified {
            get {
                return this.iNCIDENT_SEVERITY_IDFieldSpecified;
            }
            set {
                this.iNCIDENT_SEVERITY_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_ATTRIBUTE_14 {
            get {
                return this.iNCIDENT_ATTRIBUTE_14Field;
            }
            set {
                this.iNCIDENT_ATTRIBUTE_14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCIDENT_ATTRIBUTE_15 {
            get {
                return this.iNCIDENT_ATTRIBUTE_15Field;
            }
            set {
                this.iNCIDENT_ATTRIBUTE_15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CONTACT_PARTY_ID {
            get {
                return this.cONTACT_PARTY_IDField;
            }
            set {
                this.cONTACT_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CONTACT_PARTY_IDSpecified {
            get {
                return this.cONTACT_PARTY_IDFieldSpecified;
            }
            set {
                this.cONTACT_PARTY_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
        "vice_request_info/")]
    public partial class InputParameters {
        
        private string p_INCIDENT_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_INCIDENT_NUMBER {
            get {
                return this.p_INCIDENT_NUMBERField;
            }
            set {
                this.p_INCIDENT_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
        "vice_request_info/")]
    public partial class OutputParameters {
        
        private APPSCS_SERVICEREQUEX16438971X1X2 x_SERVICE_REQUEST_INFOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public APPSCS_SERVICEREQUEX16438971X1X2 X_SERVICE_REQUEST_INFO {
            get {
                return this.x_SERVICE_REQUEST_INFOField;
            }
            set {
                this.x_SERVICE_REQUEST_INFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
        "vice_request_list/")]
    public partial class InputParameters1 {
        
        private System.Nullable<decimal> p_CONTACT_PARTY_IDField;
        
        private bool p_CONTACT_PARTY_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_CONTACT_PARTY_ID {
            get {
                return this.p_CONTACT_PARTY_IDField;
            }
            set {
                this.p_CONTACT_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_CONTACT_PARTY_IDSpecified {
            get {
                return this.p_CONTACT_PARTY_IDFieldSpecified;
            }
            set {
                this.p_CONTACT_PARTY_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/csd/soaprovider/plsql/cs_servicerequest_cust/get_ser" +
        "vice_request_list/")]
    public partial class OutputParameters1 {
        
        private APPSCS_SERVICEREQUEX16438971X2X3[] x_SERVICE_REQUESTSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("X_SERVICE_REQUESTS_ITEM")]
        public APPSCS_SERVICEREQUEX16438971X2X3[] X_SERVICE_REQUESTS {
            get {
                return this.x_SERVICE_REQUESTSField;
            }
            set {
                this.x_SERVICE_REQUESTSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GET_SERVICE_REQUEST_INFOCompletedEventHandler(object sender, GET_SERVICE_REQUEST_INFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_SERVICE_REQUEST_INFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_SERVICE_REQUEST_INFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GET_SERVICE_REQUEST_LISTCompletedEventHandler(object sender, GET_SERVICE_REQUEST_LISTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_SERVICE_REQUEST_LISTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_SERVICE_REQUEST_LISTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters1)(this.results[0]));
            }
        }
    }
}
