//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Accelerator.EBS.SharedServices.ProxyClasses.Interaction {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JTF_NOTES_PUB_Binding", Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/")]
    public partial class JTF_NOTES_PUB_Service : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private SOAHeader sOAHeaderValueField;
        
        private System.Threading.SendOrPostCallback SECURE_CREATE_NOTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback SECURE_DELETE_NOTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback SECURE_UPDATE_NOTEOperationCompleted;
        
        /// <remarks/>
        public JTF_NOTES_PUB_Service() {
            this.Url = "http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/jtf_notes_pub/" +
                "";
        }
        
        public SOAHeader SOAHeaderValue {
            get {
                return this.sOAHeaderValueField;
            }
            set {
                this.sOAHeaderValueField = value;
            }
        }
        
        /// <remarks/>
        public event SECURE_CREATE_NOTECompletedEventHandler SECURE_CREATE_NOTECompleted;
        
        /// <remarks/>
        public event SECURE_DELETE_NOTECompletedEventHandler SECURE_DELETE_NOTECompleted;
        
        /// <remarks/>
        public event SECURE_UPDATE_NOTECompletedEventHandler SECURE_UPDATE_NOTECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/jtf_notes_pub/" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_create_no" +
            "te/")]
        public OutputParameters SECURE_CREATE_NOTE([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_create_no" +
            "te/")] InputParameters InputParameters) {
            object[] results = this.Invoke("SECURE_CREATE_NOTE", new object[] {
                        InputParameters});
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSECURE_CREATE_NOTE(InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SECURE_CREATE_NOTE", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters EndSECURE_CREATE_NOTE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public void SECURE_CREATE_NOTEAsync(InputParameters InputParameters) {
            this.SECURE_CREATE_NOTEAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void SECURE_CREATE_NOTEAsync(InputParameters InputParameters, object userState) {
            if ((this.SECURE_CREATE_NOTEOperationCompleted == null)) {
                this.SECURE_CREATE_NOTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSECURE_CREATE_NOTEOperationCompleted);
            }
            this.InvokeAsync("SECURE_CREATE_NOTE", new object[] {
                        InputParameters}, this.SECURE_CREATE_NOTEOperationCompleted, userState);
        }
        
        private void OnSECURE_CREATE_NOTEOperationCompleted(object arg) {
            if ((this.SECURE_CREATE_NOTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SECURE_CREATE_NOTECompleted(this, new SECURE_CREATE_NOTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/jtf_notes_pub/" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_delete_no" +
            "te/")]
        public OutputParameters1 SECURE_DELETE_NOTE([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_delete_no" +
            "te/")] InputParameters1 InputParameters) {
            object[] results = this.Invoke("SECURE_DELETE_NOTE", new object[] {
                        InputParameters});
            return ((OutputParameters1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSECURE_DELETE_NOTE(InputParameters1 InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SECURE_DELETE_NOTE", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters1 EndSECURE_DELETE_NOTE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters1)(results[0]));
        }
        
        /// <remarks/>
        public void SECURE_DELETE_NOTEAsync(InputParameters1 InputParameters) {
            this.SECURE_DELETE_NOTEAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void SECURE_DELETE_NOTEAsync(InputParameters1 InputParameters, object userState) {
            if ((this.SECURE_DELETE_NOTEOperationCompleted == null)) {
                this.SECURE_DELETE_NOTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSECURE_DELETE_NOTEOperationCompleted);
            }
            this.InvokeAsync("SECURE_DELETE_NOTE", new object[] {
                        InputParameters}, this.SECURE_DELETE_NOTEOperationCompleted, userState);
        }
        
        private void OnSECURE_DELETE_NOTEOperationCompleted(object arg) {
            if ((this.SECURE_DELETE_NOTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SECURE_DELETE_NOTECompleted(this, new SECURE_DELETE_NOTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rws3220164.us.oracle.com:8055/webservices/SOAProvider/plsql/jtf_notes_pub/" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_update_no" +
            "te/")]
        public OutputParameters2 SECURE_UPDATE_NOTE([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_update_no" +
            "te/")] InputParameters2 InputParameters) {
            object[] results = this.Invoke("SECURE_UPDATE_NOTE", new object[] {
                        InputParameters});
            return ((OutputParameters2)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSECURE_UPDATE_NOTE(InputParameters2 InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SECURE_UPDATE_NOTE", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters2 EndSECURE_UPDATE_NOTE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters2)(results[0]));
        }
        
        /// <remarks/>
        public void SECURE_UPDATE_NOTEAsync(InputParameters2 InputParameters) {
            this.SECURE_UPDATE_NOTEAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void SECURE_UPDATE_NOTEAsync(InputParameters2 InputParameters, object userState) {
            if ((this.SECURE_UPDATE_NOTEOperationCompleted == null)) {
                this.SECURE_UPDATE_NOTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSECURE_UPDATE_NOTEOperationCompleted);
            }
            this.InvokeAsync("SECURE_UPDATE_NOTE", new object[] {
                        InputParameters}, this.SECURE_UPDATE_NOTEOperationCompleted, userState);
        }
        
        private void OnSECURE_UPDATE_NOTEOperationCompleted(object arg) {
            if ((this.SECURE_UPDATE_NOTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SECURE_UPDATE_NOTECompleted(this, new SECURE_UPDATE_NOTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/", IsNullable=false)]
    public partial class SOAHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string responsibilityField;
        
        private string respApplicationField;
        
        private string securityGroupField;
        
        private string nLSLanguageField;
        
        private string org_IdField;
        
        /// <remarks/>
        public string Responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
            }
        }
        
        /// <remarks/>
        public string RespApplication {
            get {
                return this.respApplicationField;
            }
            set {
                this.respApplicationField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityGroup {
            get {
                return this.securityGroupField;
            }
            set {
                this.securityGroupField = value;
            }
        }
        
        /// <remarks/>
        public string NLSLanguage {
            get {
                return this.nLSLanguageField;
            }
            set {
                this.nLSLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.JTF_NOTES_PUB_JX227585X16X19", Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_update_no" +
        "te/")]
    public partial class APPSJTF_NOTES_PUB_JX227585X16X19 {
        
        private System.Nullable<decimal> nOTE_CONTEXT_IDField;
        
        private bool nOTE_CONTEXT_IDFieldSpecified;
        
        private System.Nullable<decimal> jTF_NOTE_IDField;
        
        private bool jTF_NOTE_IDFieldSpecified;
        
        private string nOTE_CONTEXT_TYPEField;
        
        private System.Nullable<decimal> nOTE_CONTEXT_TYPE_IDField;
        
        private bool nOTE_CONTEXT_TYPE_IDFieldSpecified;
        
        private System.Nullable<System.DateTime> lAST_UPDATE_DATEField;
        
        private bool lAST_UPDATE_DATEFieldSpecified;
        
        private System.Nullable<decimal> lAST_UPDATED_BYField;
        
        private bool lAST_UPDATED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private System.Nullable<decimal> cREATED_BYField;
        
        private bool cREATED_BYFieldSpecified;
        
        private System.Nullable<decimal> lAST_UPDATE_LOGINField;
        
        private bool lAST_UPDATE_LOGINFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NOTE_CONTEXT_ID {
            get {
                return this.nOTE_CONTEXT_IDField;
            }
            set {
                this.nOTE_CONTEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOTE_CONTEXT_IDSpecified {
            get {
                return this.nOTE_CONTEXT_IDFieldSpecified;
            }
            set {
                this.nOTE_CONTEXT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> JTF_NOTE_ID {
            get {
                return this.jTF_NOTE_IDField;
            }
            set {
                this.jTF_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JTF_NOTE_IDSpecified {
            get {
                return this.jTF_NOTE_IDFieldSpecified;
            }
            set {
                this.jTF_NOTE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOTE_CONTEXT_TYPE {
            get {
                return this.nOTE_CONTEXT_TYPEField;
            }
            set {
                this.nOTE_CONTEXT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NOTE_CONTEXT_TYPE_ID {
            get {
                return this.nOTE_CONTEXT_TYPE_IDField;
            }
            set {
                this.nOTE_CONTEXT_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOTE_CONTEXT_TYPE_IDSpecified {
            get {
                return this.nOTE_CONTEXT_TYPE_IDFieldSpecified;
            }
            set {
                this.nOTE_CONTEXT_TYPE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LAST_UPDATE_DATE {
            get {
                return this.lAST_UPDATE_DATEField;
            }
            set {
                this.lAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATE_DATESpecified {
            get {
                return this.lAST_UPDATE_DATEFieldSpecified;
            }
            set {
                this.lAST_UPDATE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LAST_UPDATED_BY {
            get {
                return this.lAST_UPDATED_BYField;
            }
            set {
                this.lAST_UPDATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATED_BYSpecified {
            get {
                return this.lAST_UPDATED_BYFieldSpecified;
            }
            set {
                this.lAST_UPDATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATED_BYSpecified {
            get {
                return this.cREATED_BYFieldSpecified;
            }
            set {
                this.cREATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LAST_UPDATE_LOGIN {
            get {
                return this.lAST_UPDATE_LOGINField;
            }
            set {
                this.lAST_UPDATE_LOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATE_LOGINSpecified {
            get {
                return this.lAST_UPDATE_LOGINFieldSpecified;
            }
            set {
                this.lAST_UPDATE_LOGINFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.JTF_NOTES_PUB_JX227585X15X42", Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_create_no" +
        "te/")]
    public partial class APPSJTF_NOTES_PUB_JX227585X15X42 {
        
        private System.Nullable<decimal> nOTE_CONTEXT_IDField;
        
        private bool nOTE_CONTEXT_IDFieldSpecified;
        
        private System.Nullable<decimal> jTF_NOTE_IDField;
        
        private bool jTF_NOTE_IDFieldSpecified;
        
        private string nOTE_CONTEXT_TYPEField;
        
        private System.Nullable<decimal> nOTE_CONTEXT_TYPE_IDField;
        
        private bool nOTE_CONTEXT_TYPE_IDFieldSpecified;
        
        private System.Nullable<System.DateTime> lAST_UPDATE_DATEField;
        
        private bool lAST_UPDATE_DATEFieldSpecified;
        
        private System.Nullable<decimal> lAST_UPDATED_BYField;
        
        private bool lAST_UPDATED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private System.Nullable<decimal> cREATED_BYField;
        
        private bool cREATED_BYFieldSpecified;
        
        private System.Nullable<decimal> lAST_UPDATE_LOGINField;
        
        private bool lAST_UPDATE_LOGINFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NOTE_CONTEXT_ID {
            get {
                return this.nOTE_CONTEXT_IDField;
            }
            set {
                this.nOTE_CONTEXT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOTE_CONTEXT_IDSpecified {
            get {
                return this.nOTE_CONTEXT_IDFieldSpecified;
            }
            set {
                this.nOTE_CONTEXT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> JTF_NOTE_ID {
            get {
                return this.jTF_NOTE_IDField;
            }
            set {
                this.jTF_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JTF_NOTE_IDSpecified {
            get {
                return this.jTF_NOTE_IDFieldSpecified;
            }
            set {
                this.jTF_NOTE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOTE_CONTEXT_TYPE {
            get {
                return this.nOTE_CONTEXT_TYPEField;
            }
            set {
                this.nOTE_CONTEXT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NOTE_CONTEXT_TYPE_ID {
            get {
                return this.nOTE_CONTEXT_TYPE_IDField;
            }
            set {
                this.nOTE_CONTEXT_TYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NOTE_CONTEXT_TYPE_IDSpecified {
            get {
                return this.nOTE_CONTEXT_TYPE_IDFieldSpecified;
            }
            set {
                this.nOTE_CONTEXT_TYPE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LAST_UPDATE_DATE {
            get {
                return this.lAST_UPDATE_DATEField;
            }
            set {
                this.lAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATE_DATESpecified {
            get {
                return this.lAST_UPDATE_DATEFieldSpecified;
            }
            set {
                this.lAST_UPDATE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LAST_UPDATED_BY {
            get {
                return this.lAST_UPDATED_BYField;
            }
            set {
                this.lAST_UPDATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATED_BYSpecified {
            get {
                return this.lAST_UPDATED_BYFieldSpecified;
            }
            set {
                this.lAST_UPDATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATED_BYSpecified {
            get {
                return this.cREATED_BYFieldSpecified;
            }
            set {
                this.cREATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LAST_UPDATE_LOGIN {
            get {
                return this.lAST_UPDATE_LOGINField;
            }
            set {
                this.lAST_UPDATE_LOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LAST_UPDATE_LOGINSpecified {
            get {
                return this.lAST_UPDATE_LOGINFieldSpecified;
            }
            set {
                this.lAST_UPDATE_LOGINFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_create_no" +
        "te/")]
    public partial class InputParameters {
        
        private System.Nullable<decimal> p_PARENT_NOTE_IDField;
        
        private bool p_PARENT_NOTE_IDFieldSpecified;
        
        private System.Nullable<decimal> p_JTF_NOTE_IDField;
        
        private bool p_JTF_NOTE_IDFieldSpecified;
        
        private System.Nullable<decimal> p_API_VERSIONField;
        
        private bool p_API_VERSIONFieldSpecified;
        
        private string p_INIT_MSG_LISTField;
        
        private string p_COMMITField;
        
        private System.Nullable<decimal> p_VALIDATION_LEVELField;
        
        private bool p_VALIDATION_LEVELFieldSpecified;
        
        private System.Nullable<decimal> p_ORG_IDField;
        
        private bool p_ORG_IDFieldSpecified;
        
        private System.Nullable<decimal> p_SOURCE_OBJECT_IDField;
        
        private bool p_SOURCE_OBJECT_IDFieldSpecified;
        
        private string p_SOURCE_OBJECT_CODEField;
        
        private string p_NOTESField;
        
        private string p_NOTES_DETAILField;
        
        private string p_NOTE_STATUSField;
        
        private System.Nullable<decimal> p_ENTERED_BYField;
        
        private bool p_ENTERED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> p_ENTERED_DATEField;
        
        private bool p_ENTERED_DATEFieldSpecified;
        
        private System.Nullable<System.DateTime> p_LAST_UPDATE_DATEField;
        
        private bool p_LAST_UPDATE_DATEFieldSpecified;
        
        private System.Nullable<decimal> p_LAST_UPDATED_BYField;
        
        private bool p_LAST_UPDATED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> p_CREATION_DATEField;
        
        private bool p_CREATION_DATEFieldSpecified;
        
        private System.Nullable<decimal> p_CREATED_BYField;
        
        private bool p_CREATED_BYFieldSpecified;
        
        private System.Nullable<decimal> p_LAST_UPDATE_LOGINField;
        
        private bool p_LAST_UPDATE_LOGINFieldSpecified;
        
        private string p_ATTRIBUTE1Field;
        
        private string p_ATTRIBUTE2Field;
        
        private string p_ATTRIBUTE3Field;
        
        private string p_ATTRIBUTE4Field;
        
        private string p_ATTRIBUTE5Field;
        
        private string p_ATTRIBUTE6Field;
        
        private string p_ATTRIBUTE7Field;
        
        private string p_ATTRIBUTE8Field;
        
        private string p_ATTRIBUTE9Field;
        
        private string p_ATTRIBUTE10Field;
        
        private string p_ATTRIBUTE11Field;
        
        private string p_ATTRIBUTE12Field;
        
        private string p_ATTRIBUTE13Field;
        
        private string p_ATTRIBUTE14Field;
        
        private string p_ATTRIBUTE15Field;
        
        private string p_CONTEXTField;
        
        private string p_NOTE_TYPEField;
        
        private APPSJTF_NOTES_PUB_JX227585X15X42[] p_JTF_NOTE_CONTEXTS_TABField;
        
        private string p_USE_AOL_SECURITYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_PARENT_NOTE_ID {
            get {
                return this.p_PARENT_NOTE_IDField;
            }
            set {
                this.p_PARENT_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_PARENT_NOTE_IDSpecified {
            get {
                return this.p_PARENT_NOTE_IDFieldSpecified;
            }
            set {
                this.p_PARENT_NOTE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_JTF_NOTE_ID {
            get {
                return this.p_JTF_NOTE_IDField;
            }
            set {
                this.p_JTF_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_JTF_NOTE_IDSpecified {
            get {
                return this.p_JTF_NOTE_IDFieldSpecified;
            }
            set {
                this.p_JTF_NOTE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_API_VERSION {
            get {
                return this.p_API_VERSIONField;
            }
            set {
                this.p_API_VERSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_API_VERSIONSpecified {
            get {
                return this.p_API_VERSIONFieldSpecified;
            }
            set {
                this.p_API_VERSIONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_INIT_MSG_LIST {
            get {
                return this.p_INIT_MSG_LISTField;
            }
            set {
                this.p_INIT_MSG_LISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_COMMIT {
            get {
                return this.p_COMMITField;
            }
            set {
                this.p_COMMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_VALIDATION_LEVEL {
            get {
                return this.p_VALIDATION_LEVELField;
            }
            set {
                this.p_VALIDATION_LEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_VALIDATION_LEVELSpecified {
            get {
                return this.p_VALIDATION_LEVELFieldSpecified;
            }
            set {
                this.p_VALIDATION_LEVELFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_ORG_ID {
            get {
                return this.p_ORG_IDField;
            }
            set {
                this.p_ORG_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ORG_IDSpecified {
            get {
                return this.p_ORG_IDFieldSpecified;
            }
            set {
                this.p_ORG_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_SOURCE_OBJECT_ID {
            get {
                return this.p_SOURCE_OBJECT_IDField;
            }
            set {
                this.p_SOURCE_OBJECT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_SOURCE_OBJECT_IDSpecified {
            get {
                return this.p_SOURCE_OBJECT_IDFieldSpecified;
            }
            set {
                this.p_SOURCE_OBJECT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_SOURCE_OBJECT_CODE {
            get {
                return this.p_SOURCE_OBJECT_CODEField;
            }
            set {
                this.p_SOURCE_OBJECT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTES {
            get {
                return this.p_NOTESField;
            }
            set {
                this.p_NOTESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTES_DETAIL {
            get {
                return this.p_NOTES_DETAILField;
            }
            set {
                this.p_NOTES_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTE_STATUS {
            get {
                return this.p_NOTE_STATUSField;
            }
            set {
                this.p_NOTE_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_ENTERED_BY {
            get {
                return this.p_ENTERED_BYField;
            }
            set {
                this.p_ENTERED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ENTERED_BYSpecified {
            get {
                return this.p_ENTERED_BYFieldSpecified;
            }
            set {
                this.p_ENTERED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> P_ENTERED_DATE {
            get {
                return this.p_ENTERED_DATEField;
            }
            set {
                this.p_ENTERED_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ENTERED_DATESpecified {
            get {
                return this.p_ENTERED_DATEFieldSpecified;
            }
            set {
                this.p_ENTERED_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> P_LAST_UPDATE_DATE {
            get {
                return this.p_LAST_UPDATE_DATEField;
            }
            set {
                this.p_LAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LAST_UPDATE_DATESpecified {
            get {
                return this.p_LAST_UPDATE_DATEFieldSpecified;
            }
            set {
                this.p_LAST_UPDATE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_LAST_UPDATED_BY {
            get {
                return this.p_LAST_UPDATED_BYField;
            }
            set {
                this.p_LAST_UPDATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LAST_UPDATED_BYSpecified {
            get {
                return this.p_LAST_UPDATED_BYFieldSpecified;
            }
            set {
                this.p_LAST_UPDATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> P_CREATION_DATE {
            get {
                return this.p_CREATION_DATEField;
            }
            set {
                this.p_CREATION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_CREATION_DATESpecified {
            get {
                return this.p_CREATION_DATEFieldSpecified;
            }
            set {
                this.p_CREATION_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_CREATED_BY {
            get {
                return this.p_CREATED_BYField;
            }
            set {
                this.p_CREATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_CREATED_BYSpecified {
            get {
                return this.p_CREATED_BYFieldSpecified;
            }
            set {
                this.p_CREATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_LAST_UPDATE_LOGIN {
            get {
                return this.p_LAST_UPDATE_LOGINField;
            }
            set {
                this.p_LAST_UPDATE_LOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LAST_UPDATE_LOGINSpecified {
            get {
                return this.p_LAST_UPDATE_LOGINFieldSpecified;
            }
            set {
                this.p_LAST_UPDATE_LOGINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE1 {
            get {
                return this.p_ATTRIBUTE1Field;
            }
            set {
                this.p_ATTRIBUTE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE2 {
            get {
                return this.p_ATTRIBUTE2Field;
            }
            set {
                this.p_ATTRIBUTE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE3 {
            get {
                return this.p_ATTRIBUTE3Field;
            }
            set {
                this.p_ATTRIBUTE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE4 {
            get {
                return this.p_ATTRIBUTE4Field;
            }
            set {
                this.p_ATTRIBUTE4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE5 {
            get {
                return this.p_ATTRIBUTE5Field;
            }
            set {
                this.p_ATTRIBUTE5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE6 {
            get {
                return this.p_ATTRIBUTE6Field;
            }
            set {
                this.p_ATTRIBUTE6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE7 {
            get {
                return this.p_ATTRIBUTE7Field;
            }
            set {
                this.p_ATTRIBUTE7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE8 {
            get {
                return this.p_ATTRIBUTE8Field;
            }
            set {
                this.p_ATTRIBUTE8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE9 {
            get {
                return this.p_ATTRIBUTE9Field;
            }
            set {
                this.p_ATTRIBUTE9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE10 {
            get {
                return this.p_ATTRIBUTE10Field;
            }
            set {
                this.p_ATTRIBUTE10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE11 {
            get {
                return this.p_ATTRIBUTE11Field;
            }
            set {
                this.p_ATTRIBUTE11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE12 {
            get {
                return this.p_ATTRIBUTE12Field;
            }
            set {
                this.p_ATTRIBUTE12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE13 {
            get {
                return this.p_ATTRIBUTE13Field;
            }
            set {
                this.p_ATTRIBUTE13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE14 {
            get {
                return this.p_ATTRIBUTE14Field;
            }
            set {
                this.p_ATTRIBUTE14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE15 {
            get {
                return this.p_ATTRIBUTE15Field;
            }
            set {
                this.p_ATTRIBUTE15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_CONTEXT {
            get {
                return this.p_CONTEXTField;
            }
            set {
                this.p_CONTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTE_TYPE {
            get {
                return this.p_NOTE_TYPEField;
            }
            set {
                this.p_NOTE_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("P_JTF_NOTE_CONTEXTS_TAB_ITEM")]
        public APPSJTF_NOTES_PUB_JX227585X15X42[] P_JTF_NOTE_CONTEXTS_TAB {
            get {
                return this.p_JTF_NOTE_CONTEXTS_TABField;
            }
            set {
                this.p_JTF_NOTE_CONTEXTS_TABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_USE_AOL_SECURITY {
            get {
                return this.p_USE_AOL_SECURITYField;
            }
            set {
                this.p_USE_AOL_SECURITYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_create_no" +
        "te/")]
    public partial class OutputParameters {
        
        private string x_RETURN_STATUSField;
        
        private System.Nullable<decimal> x_MSG_COUNTField;
        
        private bool x_MSG_COUNTFieldSpecified;
        
        private string x_MSG_DATAField;
        
        private System.Nullable<decimal> x_JTF_NOTE_IDField;
        
        private bool x_JTF_NOTE_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_RETURN_STATUS {
            get {
                return this.x_RETURN_STATUSField;
            }
            set {
                this.x_RETURN_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> X_MSG_COUNT {
            get {
                return this.x_MSG_COUNTField;
            }
            set {
                this.x_MSG_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X_MSG_COUNTSpecified {
            get {
                return this.x_MSG_COUNTFieldSpecified;
            }
            set {
                this.x_MSG_COUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_MSG_DATA {
            get {
                return this.x_MSG_DATAField;
            }
            set {
                this.x_MSG_DATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> X_JTF_NOTE_ID {
            get {
                return this.x_JTF_NOTE_IDField;
            }
            set {
                this.x_JTF_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X_JTF_NOTE_IDSpecified {
            get {
                return this.x_JTF_NOTE_IDFieldSpecified;
            }
            set {
                this.x_JTF_NOTE_IDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_delete_no" +
        "te/")]
    public partial class InputParameters1 {
        
        private System.Nullable<decimal> p_API_VERSIONField;
        
        private bool p_API_VERSIONFieldSpecified;
        
        private string p_INIT_MSG_LISTField;
        
        private string p_COMMITField;
        
        private System.Nullable<decimal> p_VALIDATION_LEVELField;
        
        private bool p_VALIDATION_LEVELFieldSpecified;
        
        private System.Nullable<decimal> p_JTF_NOTE_IDField;
        
        private bool p_JTF_NOTE_IDFieldSpecified;
        
        private string p_USE_AOL_SECURITYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_API_VERSION {
            get {
                return this.p_API_VERSIONField;
            }
            set {
                this.p_API_VERSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_API_VERSIONSpecified {
            get {
                return this.p_API_VERSIONFieldSpecified;
            }
            set {
                this.p_API_VERSIONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_INIT_MSG_LIST {
            get {
                return this.p_INIT_MSG_LISTField;
            }
            set {
                this.p_INIT_MSG_LISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_COMMIT {
            get {
                return this.p_COMMITField;
            }
            set {
                this.p_COMMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_VALIDATION_LEVEL {
            get {
                return this.p_VALIDATION_LEVELField;
            }
            set {
                this.p_VALIDATION_LEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_VALIDATION_LEVELSpecified {
            get {
                return this.p_VALIDATION_LEVELFieldSpecified;
            }
            set {
                this.p_VALIDATION_LEVELFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_JTF_NOTE_ID {
            get {
                return this.p_JTF_NOTE_IDField;
            }
            set {
                this.p_JTF_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_JTF_NOTE_IDSpecified {
            get {
                return this.p_JTF_NOTE_IDFieldSpecified;
            }
            set {
                this.p_JTF_NOTE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_USE_AOL_SECURITY {
            get {
                return this.p_USE_AOL_SECURITYField;
            }
            set {
                this.p_USE_AOL_SECURITYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_delete_no" +
        "te/")]
    public partial class OutputParameters1 {
        
        private string x_RETURN_STATUSField;
        
        private System.Nullable<decimal> x_MSG_COUNTField;
        
        private bool x_MSG_COUNTFieldSpecified;
        
        private string x_MSG_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_RETURN_STATUS {
            get {
                return this.x_RETURN_STATUSField;
            }
            set {
                this.x_RETURN_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> X_MSG_COUNT {
            get {
                return this.x_MSG_COUNTField;
            }
            set {
                this.x_MSG_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X_MSG_COUNTSpecified {
            get {
                return this.x_MSG_COUNTFieldSpecified;
            }
            set {
                this.x_MSG_COUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_MSG_DATA {
            get {
                return this.x_MSG_DATAField;
            }
            set {
                this.x_MSG_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_update_no" +
        "te/")]
    public partial class InputParameters2 {
        
        private System.Nullable<decimal> p_API_VERSIONField;
        
        private bool p_API_VERSIONFieldSpecified;
        
        private string p_INIT_MSG_LISTField;
        
        private string p_COMMITField;
        
        private System.Nullable<decimal> p_VALIDATION_LEVELField;
        
        private bool p_VALIDATION_LEVELFieldSpecified;
        
        private System.Nullable<decimal> p_JTF_NOTE_IDField;
        
        private bool p_JTF_NOTE_IDFieldSpecified;
        
        private System.Nullable<decimal> p_ENTERED_BYField;
        
        private bool p_ENTERED_BYFieldSpecified;
        
        private System.Nullable<decimal> p_LAST_UPDATED_BYField;
        
        private bool p_LAST_UPDATED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> p_LAST_UPDATE_DATEField;
        
        private bool p_LAST_UPDATE_DATEFieldSpecified;
        
        private System.Nullable<decimal> p_LAST_UPDATE_LOGINField;
        
        private bool p_LAST_UPDATE_LOGINFieldSpecified;
        
        private string p_NOTESField;
        
        private string p_NOTES_DETAILField;
        
        private string p_APPEND_FLAGField;
        
        private string p_NOTE_STATUSField;
        
        private string p_NOTE_TYPEField;
        
        private APPSJTF_NOTES_PUB_JX227585X16X19[] p_JTF_NOTE_CONTEXTS_TABField;
        
        private string p_ATTRIBUTE1Field;
        
        private string p_ATTRIBUTE2Field;
        
        private string p_ATTRIBUTE3Field;
        
        private string p_ATTRIBUTE4Field;
        
        private string p_ATTRIBUTE5Field;
        
        private string p_ATTRIBUTE6Field;
        
        private string p_ATTRIBUTE7Field;
        
        private string p_ATTRIBUTE8Field;
        
        private string p_ATTRIBUTE9Field;
        
        private string p_ATTRIBUTE10Field;
        
        private string p_ATTRIBUTE11Field;
        
        private string p_ATTRIBUTE12Field;
        
        private string p_ATTRIBUTE13Field;
        
        private string p_ATTRIBUTE14Field;
        
        private string p_ATTRIBUTE15Field;
        
        private string p_CONTEXTField;
        
        private string p_USE_AOL_SECURITYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_API_VERSION {
            get {
                return this.p_API_VERSIONField;
            }
            set {
                this.p_API_VERSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_API_VERSIONSpecified {
            get {
                return this.p_API_VERSIONFieldSpecified;
            }
            set {
                this.p_API_VERSIONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_INIT_MSG_LIST {
            get {
                return this.p_INIT_MSG_LISTField;
            }
            set {
                this.p_INIT_MSG_LISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_COMMIT {
            get {
                return this.p_COMMITField;
            }
            set {
                this.p_COMMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_VALIDATION_LEVEL {
            get {
                return this.p_VALIDATION_LEVELField;
            }
            set {
                this.p_VALIDATION_LEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_VALIDATION_LEVELSpecified {
            get {
                return this.p_VALIDATION_LEVELFieldSpecified;
            }
            set {
                this.p_VALIDATION_LEVELFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_JTF_NOTE_ID {
            get {
                return this.p_JTF_NOTE_IDField;
            }
            set {
                this.p_JTF_NOTE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_JTF_NOTE_IDSpecified {
            get {
                return this.p_JTF_NOTE_IDFieldSpecified;
            }
            set {
                this.p_JTF_NOTE_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_ENTERED_BY {
            get {
                return this.p_ENTERED_BYField;
            }
            set {
                this.p_ENTERED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ENTERED_BYSpecified {
            get {
                return this.p_ENTERED_BYFieldSpecified;
            }
            set {
                this.p_ENTERED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_LAST_UPDATED_BY {
            get {
                return this.p_LAST_UPDATED_BYField;
            }
            set {
                this.p_LAST_UPDATED_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LAST_UPDATED_BYSpecified {
            get {
                return this.p_LAST_UPDATED_BYFieldSpecified;
            }
            set {
                this.p_LAST_UPDATED_BYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> P_LAST_UPDATE_DATE {
            get {
                return this.p_LAST_UPDATE_DATEField;
            }
            set {
                this.p_LAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LAST_UPDATE_DATESpecified {
            get {
                return this.p_LAST_UPDATE_DATEFieldSpecified;
            }
            set {
                this.p_LAST_UPDATE_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_LAST_UPDATE_LOGIN {
            get {
                return this.p_LAST_UPDATE_LOGINField;
            }
            set {
                this.p_LAST_UPDATE_LOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LAST_UPDATE_LOGINSpecified {
            get {
                return this.p_LAST_UPDATE_LOGINFieldSpecified;
            }
            set {
                this.p_LAST_UPDATE_LOGINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTES {
            get {
                return this.p_NOTESField;
            }
            set {
                this.p_NOTESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTES_DETAIL {
            get {
                return this.p_NOTES_DETAILField;
            }
            set {
                this.p_NOTES_DETAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_APPEND_FLAG {
            get {
                return this.p_APPEND_FLAGField;
            }
            set {
                this.p_APPEND_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTE_STATUS {
            get {
                return this.p_NOTE_STATUSField;
            }
            set {
                this.p_NOTE_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_NOTE_TYPE {
            get {
                return this.p_NOTE_TYPEField;
            }
            set {
                this.p_NOTE_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("P_JTF_NOTE_CONTEXTS_TAB_ITEM")]
        public APPSJTF_NOTES_PUB_JX227585X16X19[] P_JTF_NOTE_CONTEXTS_TAB {
            get {
                return this.p_JTF_NOTE_CONTEXTS_TABField;
            }
            set {
                this.p_JTF_NOTE_CONTEXTS_TABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE1 {
            get {
                return this.p_ATTRIBUTE1Field;
            }
            set {
                this.p_ATTRIBUTE1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE2 {
            get {
                return this.p_ATTRIBUTE2Field;
            }
            set {
                this.p_ATTRIBUTE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE3 {
            get {
                return this.p_ATTRIBUTE3Field;
            }
            set {
                this.p_ATTRIBUTE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE4 {
            get {
                return this.p_ATTRIBUTE4Field;
            }
            set {
                this.p_ATTRIBUTE4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE5 {
            get {
                return this.p_ATTRIBUTE5Field;
            }
            set {
                this.p_ATTRIBUTE5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE6 {
            get {
                return this.p_ATTRIBUTE6Field;
            }
            set {
                this.p_ATTRIBUTE6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE7 {
            get {
                return this.p_ATTRIBUTE7Field;
            }
            set {
                this.p_ATTRIBUTE7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE8 {
            get {
                return this.p_ATTRIBUTE8Field;
            }
            set {
                this.p_ATTRIBUTE8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE9 {
            get {
                return this.p_ATTRIBUTE9Field;
            }
            set {
                this.p_ATTRIBUTE9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE10 {
            get {
                return this.p_ATTRIBUTE10Field;
            }
            set {
                this.p_ATTRIBUTE10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE11 {
            get {
                return this.p_ATTRIBUTE11Field;
            }
            set {
                this.p_ATTRIBUTE11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE12 {
            get {
                return this.p_ATTRIBUTE12Field;
            }
            set {
                this.p_ATTRIBUTE12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE13 {
            get {
                return this.p_ATTRIBUTE13Field;
            }
            set {
                this.p_ATTRIBUTE13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE14 {
            get {
                return this.p_ATTRIBUTE14Field;
            }
            set {
                this.p_ATTRIBUTE14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_ATTRIBUTE15 {
            get {
                return this.p_ATTRIBUTE15Field;
            }
            set {
                this.p_ATTRIBUTE15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_CONTEXT {
            get {
                return this.p_CONTEXTField;
            }
            set {
                this.p_CONTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_USE_AOL_SECURITY {
            get {
                return this.p_USE_AOL_SECURITYField;
            }
            set {
                this.p_USE_AOL_SECURITYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cac/soaprovider/plsql/jtf_notes_pub/secure_update_no" +
        "te/")]
    public partial class OutputParameters2 {
        
        private string x_RETURN_STATUSField;
        
        private System.Nullable<decimal> x_MSG_COUNTField;
        
        private bool x_MSG_COUNTFieldSpecified;
        
        private string x_MSG_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_RETURN_STATUS {
            get {
                return this.x_RETURN_STATUSField;
            }
            set {
                this.x_RETURN_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> X_MSG_COUNT {
            get {
                return this.x_MSG_COUNTField;
            }
            set {
                this.x_MSG_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X_MSG_COUNTSpecified {
            get {
                return this.x_MSG_COUNTFieldSpecified;
            }
            set {
                this.x_MSG_COUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_MSG_DATA {
            get {
                return this.x_MSG_DATAField;
            }
            set {
                this.x_MSG_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SECURE_CREATE_NOTECompletedEventHandler(object sender, SECURE_CREATE_NOTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SECURE_CREATE_NOTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SECURE_CREATE_NOTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SECURE_DELETE_NOTECompletedEventHandler(object sender, SECURE_DELETE_NOTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SECURE_DELETE_NOTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SECURE_DELETE_NOTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SECURE_UPDATE_NOTECompletedEventHandler(object sender, SECURE_UPDATE_NOTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SECURE_UPDATE_NOTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SECURE_UPDATE_NOTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters2)(this.results[0]));
            }
        }
    }
}
