//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerator.SRM.SharedServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accelerator.SRM.SharedServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Accelerator Add-Ins are not initialized properly. Please contact your system administrator..
        /// </summary>
        public static string AcceleratorNotInitializedNotifyAdminError {
            get {
                return ResourceManager.GetString("AcceleratorNotInitializedNotifyAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied. Agent Session is not Valid..
        /// </summary>
        public static string AccessDeniedError {
            get {
                return ResourceManager.GetString("AccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Accelerator Add-Ins are not initialized properly because of invalid config verb..
        /// </summary>
        public static string AccleratorNotInitializedConfigVerbError {
            get {
                return ResourceManager.GetString("AccleratorNotInitializedConfigVerbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a communication error. Please check the logs for details..
        /// </summary>
        public static string CommunicationErrorMessage {
            get {
                return ResourceManager.GetString("CommunicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error performing GET request.
        /// </summary>
        public static string GETErrorMessage {
            get {
                return ResourceManager.GetString("GETErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request GET OAuth Token.
        /// </summary>
        public static string GETOAuthTokenRequestMessage {
            get {
                return ResourceManager.GetString("GETOAuthTokenRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request GET Agent Session.
        /// </summary>
        public static string GETRequestAgentSessionMessage {
            get {
                return ResourceManager.GetString("GETRequestAgentSessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request GET Conversation Messages: .
        /// </summary>
        public static string GETRequestMessage {
            get {
                return ResourceManager.GetString("GETRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response GET Conversation Messages: .
        /// </summary>
        public static string GETResponseMessage {
            get {
                return ResourceManager.GetString("GETResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Token Used From Local Cache.
        /// </summary>
        public static string OAuthLocalCacheMessage {
            get {
                return ResourceManager.GetString("OAuthLocalCacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Token Used From Server.
        /// </summary>
        public static string OAuthRemoteMessage {
            get {
                return ResourceManager.GetString("OAuthRemoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get OAuth Token.
        /// </summary>
        public static string OAuthTokenError {
            get {
                return ResourceManager.GetString("OAuthTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error performing POST request.
        /// </summary>
        public static string POSTErrorMessage {
            get {
                return ResourceManager.GetString("POSTErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request POST Conversation Messages: .
        /// </summary>
        public static string POSTRequestMessage {
            get {
                return ResourceManager.GetString("POSTRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response POST Conversation Messages: .
        /// </summary>
        public static string POSTResponseMessage {
            get {
                return ResourceManager.GetString("POSTResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error performing PUT request.
        /// </summary>
        public static string PUTErrorMessage {
            get {
                return ResourceManager.GetString("PUTErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request PUT Converstaion Messages: .
        /// </summary>
        public static string PUTRequestMessage {
            get {
                return ResourceManager.GetString("PUTRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response PUT Conversation Messages: .
        /// </summary>
        public static string PUTResponseMessage {
            get {
                return ResourceManager.GetString("PUTResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens were removed from DB..
        /// </summary>
        public static string RemovedTokenLabel {
            get {
                return ResourceManager.GetString("RemovedTokenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing refresh and access token due to invalid responses from SRM.  Admin will need to reconfigure SRM credentials.
        /// </summary>
        public static string RemovingTokenNoticeLabel {
            get {
                return ResourceManager.GetString("RemovingTokenNoticeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRM oauth configs have not been configured yet. Would you like to configure them now? Delay in configuration may cause SRM add-in errors..
        /// </summary>
        public static string ServerConfigsDoNotExistAdminLabel {
            get {
                return ResourceManager.GetString("ServerConfigsDoNotExistAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRM oauth configs are not setup. Contact your administrator to configure SRM..
        /// </summary>
        public static string ServerConfigsDoNotExistUserLabel {
            get {
                return ResourceManager.GetString("ServerConfigsDoNotExistUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRM Token Configuration.
        /// </summary>
        public static string SRMTokenConfigLabel {
            get {
                return ResourceManager.GetString("SRMTokenConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRM Token Configuration Rejected by User.
        /// </summary>
        public static string SRMTokenConfigRejectedError {
            get {
                return ResourceManager.GetString("SRMTokenConfigRejectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting SRM token.
        /// </summary>
        public static string SRMTokenErrorMessage {
            get {
                return ResourceManager.GetString("SRMTokenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not setup an SRM token yet.  Would you like to do that now?  If you delay, SRM features will not work..
        /// </summary>
        public static string UserTokenDoesNotExistLabel {
            get {
                return ResourceManager.GetString("UserTokenDoesNotExistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating the SRM oauth configs.  Please run setup..
        /// </summary>
        public static string ValidatingServerConfigsError {
            get {
                return ResourceManager.GetString("ValidatingServerConfigsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating the oauth server configs have been configured..
        /// </summary>
        public static string ValidatingServerConfigsLabel {
            get {
                return ResourceManager.GetString("ValidatingServerConfigsLabel", resourceCulture);
            }
        }
    }
}
