//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerator.SRM.CreateReplyAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accelerator.SRM.CreateReplyAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddIn16 {
            get {
                object obj = ResourceManager.GetObject("AddIn16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the contact of a social incident will reassign the social handle: {0} as well..
        /// </summary>
        internal static string ChangeContactReassignMessage {
            get {
                return ResourceManager.GetString("ChangeContactReassignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have Character Limit for current incident&apos;s threads..
        /// </summary>
        internal static string CharacterLimitError {
            get {
                return ResourceManager.GetString("CharacterLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error communicating with SRM. Please check log for detail..
        /// </summary>
        internal static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constraints of current incident&apos;s conversation channel ({0}) is not defined in Config Verb..
        /// </summary>
        internal static string ConstraintsNotDefinedError {
            get {
                return ResourceManager.GetString("ConstraintsNotDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident&apos;s Contact does not match SocialChannelAccount&apos;s Contact.
        /// </summary>
        internal static string ContactDoesNotMatchSocialError {
            get {
                return ResourceManager.GetString("ContactDoesNotMatchSocialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactId is empty for SocialChannelAccount.ID {0}.
        /// </summary>
        internal static string ContactIDEmptyError {
            get {
                return ResourceManager.GetString("ContactIDEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content is longer than the {0} character limit imposed by {1}.
        /// </summary>
        internal static string ContentLongerError {
            get {
                return ResourceManager.GetString("ContentLongerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign all incidents from social handle: {0} to the selected contact?.
        /// </summary>
        internal static string ReassignAllIncidentsMessage {
            get {
                return ResourceManager.GetString("ReassignAllIncidentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srm_social_channel_account_id for incident ID: {0} is empty.
        /// </summary>
        internal static string SocialChannelEmptyError {
            get {
                return ResourceManager.GetString("SocialChannelEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srm_social_channel_account_id not found in Accelerator.SocialChannelAccount.Id.
        /// </summary>
        internal static string SRMNotFoundError {
            get {
                return ResourceManager.GetString("SRMNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Incident Id: {0} with ContactId: {1}.
        /// </summary>
        internal static string UpdateIncidentMessage {
            get {
                return ResourceManager.GetString("UpdateIncidentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SocialChannelAccount Id: {0} with ContactId: {1}.
        /// </summary>
        internal static string UpdateSocialChannelMessage {
            get {
                return ResourceManager.GetString("UpdateSocialChannelMessage", resourceCulture);
            }
        }
    }
}
