//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Accelerator.EBS.SharedServices.ProxyClasses.Contact {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HZ_INTEGRATION_PUB_Binding", Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/")]
    public partial class HZ_INTEGRATION_PUB_Service : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private SOAHeader sOAHeaderValueField;
        
        private System.Threading.SendOrPostCallback GET_CONTACT_DETAILOperationCompleted;
        
        /// <remarks/>
        public HZ_INTEGRATION_PUB_Service() {
            this.Url = "http://ebs.example.com:8000/webservices/SOAProvider/plsql/hz_integration_pub/";
        }
        
        public SOAHeader SOAHeaderValue {
            get {
                return this.sOAHeaderValueField;
            }
            set {
                this.sOAHeaderValueField = value;
            }
        }
        
        /// <remarks/>
        public event GET_CONTACT_DETAILCompletedEventHandler GET_CONTACT_DETAILCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ebs.example.com:8000/webservices/SOAProvider/plsql/hz_integration_pub/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OutputParameters", Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/get_contact_" +
            "detail/")]
        public OutputParameters GET_CONTACT_DETAIL([System.Xml.Serialization.XmlElementAttribute(Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/get_contact_" +
            "detail/")] InputParameters InputParameters) {
            object[] results = this.Invoke("GET_CONTACT_DETAIL", new object[] {
                        InputParameters});
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGET_CONTACT_DETAIL(InputParameters InputParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GET_CONTACT_DETAIL", new object[] {
                        InputParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public OutputParameters EndGET_CONTACT_DETAIL(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OutputParameters)(results[0]));
        }
        
        /// <remarks/>
        public void GET_CONTACT_DETAILAsync(InputParameters InputParameters) {
            this.GET_CONTACT_DETAILAsync(InputParameters, null);
        }
        
        /// <remarks/>
        public void GET_CONTACT_DETAILAsync(InputParameters InputParameters, object userState) {
            if ((this.GET_CONTACT_DETAILOperationCompleted == null)) {
                this.GET_CONTACT_DETAILOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_CONTACT_DETAILOperationCompleted);
            }
            this.InvokeAsync("GET_CONTACT_DETAIL", new object[] {
                        InputParameters}, this.GET_CONTACT_DETAILOperationCompleted, userState);
        }
        
        private void OnGET_CONTACT_DETAILOperationCompleted(object arg) {
            if ((this.GET_CONTACT_DETAILCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_CONTACT_DETAILCompleted(this, new GET_CONTACT_DETAILCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/", IsNullable=false)]
    public partial class SOAHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string responsibilityField;
        
        private string respApplicationField;
        
        private string securityGroupField;
        
        private string nLSLanguageField;
        
        private string org_IdField;
        
        /// <remarks/>
        public string Responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
            }
        }
        
        /// <remarks/>
        public string RespApplication {
            get {
                return this.respApplicationField;
            }
            set {
                this.respApplicationField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityGroup {
            get {
                return this.securityGroupField;
            }
            set {
                this.securityGroupField = value;
            }
        }
        
        /// <remarks/>
        public string NLSLanguage {
            get {
                return this.nLSLanguageField;
            }
            set {
                this.nLSLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.HZ_INTEGRATION_PX3348183X1X7", Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/get_contact_" +
        "detail/")]
    public partial class APPSHZ_INTEGRATION_PX3348183X1X7 {
        
        private System.Nullable<decimal> pERSON_PARTY_IDField;
        
        private bool pERSON_PARTY_IDFieldSpecified;
        
        private string pERSON_PARTY_NUMBERField;
        
        private string pERSON_FIRST_NAMEField;
        
        private string pERSON_MIDDLE_NAMEField;
        
        private string pERSON_LAST_NAMEField;
        
        private System.Nullable<decimal> oRG_PARTY_IDField;
        
        private bool oRG_PARTY_IDFieldSpecified;
        
        private string oRG_NAMEField;
        
        private string oRG_PARTY_NUMBERField;
        
        private System.Nullable<decimal> rELATIONSHIP_IDField;
        
        private bool rELATIONSHIP_IDFieldSpecified;
        
        private System.Nullable<decimal> rELATIONSHIP_PARTY_IDField;
        
        private bool rELATIONSHIP_PARTY_IDFieldSpecified;
        
        private string rELATIONSHIP_TYPEField;
        
        private string rELATIONSHIP_TYPE_MEANINGField;
        
        private string rELATIONSHIP_CODEField;
        
        private string rELATIONSHIP_CODE_MEANINGField;
        
        private string rELATIONSHIP_CREATION_DTField;
        
        private System.Nullable<decimal> oRG_CONTACT_IDField;
        
        private bool oRG_CONTACT_IDFieldSpecified;
        
        private string jOB_TITLEField;
        
        private string dEPARTMENTField;
        
        private string pRIMARY_PHONEField;
        
        private string pRIMARY_EMAILField;
        
        private string pRIMARY_ADDRESS_LINE_1Field;
        
        private string pRIMARY_ADDRESS_LINE_2Field;
        
        private string pRIMARY_ADDRESS_LINE_3Field;
        
        private string pRIMARY_ADDRESS_LINE_4Field;
        
        private string pRIMARY_CITYField;
        
        private string pRIMARY_STATEField;
        
        private string pRIMARY_PROVINCEField;
        
        private string pRIMARY_POSTAL_CODEField;
        
        private string pRIMARY_COUNTRYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PERSON_PARTY_ID {
            get {
                return this.pERSON_PARTY_IDField;
            }
            set {
                this.pERSON_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PERSON_PARTY_IDSpecified {
            get {
                return this.pERSON_PARTY_IDFieldSpecified;
            }
            set {
                this.pERSON_PARTY_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PERSON_PARTY_NUMBER {
            get {
                return this.pERSON_PARTY_NUMBERField;
            }
            set {
                this.pERSON_PARTY_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PERSON_FIRST_NAME {
            get {
                return this.pERSON_FIRST_NAMEField;
            }
            set {
                this.pERSON_FIRST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PERSON_MIDDLE_NAME {
            get {
                return this.pERSON_MIDDLE_NAMEField;
            }
            set {
                this.pERSON_MIDDLE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PERSON_LAST_NAME {
            get {
                return this.pERSON_LAST_NAMEField;
            }
            set {
                this.pERSON_LAST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORG_PARTY_ID {
            get {
                return this.oRG_PARTY_IDField;
            }
            set {
                this.oRG_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORG_PARTY_IDSpecified {
            get {
                return this.oRG_PARTY_IDFieldSpecified;
            }
            set {
                this.oRG_PARTY_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORG_NAME {
            get {
                return this.oRG_NAMEField;
            }
            set {
                this.oRG_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORG_PARTY_NUMBER {
            get {
                return this.oRG_PARTY_NUMBERField;
            }
            set {
                this.oRG_PARTY_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> RELATIONSHIP_ID {
            get {
                return this.rELATIONSHIP_IDField;
            }
            set {
                this.rELATIONSHIP_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RELATIONSHIP_IDSpecified {
            get {
                return this.rELATIONSHIP_IDFieldSpecified;
            }
            set {
                this.rELATIONSHIP_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> RELATIONSHIP_PARTY_ID {
            get {
                return this.rELATIONSHIP_PARTY_IDField;
            }
            set {
                this.rELATIONSHIP_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RELATIONSHIP_PARTY_IDSpecified {
            get {
                return this.rELATIONSHIP_PARTY_IDFieldSpecified;
            }
            set {
                this.rELATIONSHIP_PARTY_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RELATIONSHIP_TYPE {
            get {
                return this.rELATIONSHIP_TYPEField;
            }
            set {
                this.rELATIONSHIP_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RELATIONSHIP_TYPE_MEANING {
            get {
                return this.rELATIONSHIP_TYPE_MEANINGField;
            }
            set {
                this.rELATIONSHIP_TYPE_MEANINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RELATIONSHIP_CODE {
            get {
                return this.rELATIONSHIP_CODEField;
            }
            set {
                this.rELATIONSHIP_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RELATIONSHIP_CODE_MEANING {
            get {
                return this.rELATIONSHIP_CODE_MEANINGField;
            }
            set {
                this.rELATIONSHIP_CODE_MEANINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RELATIONSHIP_CREATION_DT {
            get {
                return this.rELATIONSHIP_CREATION_DTField;
            }
            set {
                this.rELATIONSHIP_CREATION_DTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORG_CONTACT_ID {
            get {
                return this.oRG_CONTACT_IDField;
            }
            set {
                this.oRG_CONTACT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORG_CONTACT_IDSpecified {
            get {
                return this.oRG_CONTACT_IDFieldSpecified;
            }
            set {
                this.oRG_CONTACT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JOB_TITLE {
            get {
                return this.jOB_TITLEField;
            }
            set {
                this.jOB_TITLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_PHONE {
            get {
                return this.pRIMARY_PHONEField;
            }
            set {
                this.pRIMARY_PHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_EMAIL {
            get {
                return this.pRIMARY_EMAILField;
            }
            set {
                this.pRIMARY_EMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_ADDRESS_LINE_1 {
            get {
                return this.pRIMARY_ADDRESS_LINE_1Field;
            }
            set {
                this.pRIMARY_ADDRESS_LINE_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_ADDRESS_LINE_2 {
            get {
                return this.pRIMARY_ADDRESS_LINE_2Field;
            }
            set {
                this.pRIMARY_ADDRESS_LINE_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_ADDRESS_LINE_3 {
            get {
                return this.pRIMARY_ADDRESS_LINE_3Field;
            }
            set {
                this.pRIMARY_ADDRESS_LINE_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_ADDRESS_LINE_4 {
            get {
                return this.pRIMARY_ADDRESS_LINE_4Field;
            }
            set {
                this.pRIMARY_ADDRESS_LINE_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_CITY {
            get {
                return this.pRIMARY_CITYField;
            }
            set {
                this.pRIMARY_CITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_STATE {
            get {
                return this.pRIMARY_STATEField;
            }
            set {
                this.pRIMARY_STATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_PROVINCE {
            get {
                return this.pRIMARY_PROVINCEField;
            }
            set {
                this.pRIMARY_PROVINCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_POSTAL_CODE {
            get {
                return this.pRIMARY_POSTAL_CODEField;
            }
            set {
                this.pRIMARY_POSTAL_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRIMARY_COUNTRY {
            get {
                return this.pRIMARY_COUNTRYField;
            }
            set {
                this.pRIMARY_COUNTRYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/get_contact_" +
        "detail/")]
    public partial class InputParameters {
        
        private System.Nullable<decimal> p_PARTY_IDField;
        
        private bool p_PARTY_IDFieldSpecified;
        
        private System.Nullable<decimal> p_ORG_CONTACT_IDField;
        
        private bool p_ORG_CONTACT_IDFieldSpecified;
        
        private string p_PHONEField;
        
        private string p_EMAILField;
        
        private System.Nullable<decimal> p_RECORD_LIMITField;
        
        private bool p_RECORD_LIMITFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_PARTY_ID {
            get {
                return this.p_PARTY_IDField;
            }
            set {
                this.p_PARTY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_PARTY_IDSpecified {
            get {
                return this.p_PARTY_IDFieldSpecified;
            }
            set {
                this.p_PARTY_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_ORG_CONTACT_ID {
            get {
                return this.p_ORG_CONTACT_IDField;
            }
            set {
                this.p_ORG_CONTACT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ORG_CONTACT_IDSpecified {
            get {
                return this.p_ORG_CONTACT_IDFieldSpecified;
            }
            set {
                this.p_ORG_CONTACT_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_PHONE {
            get {
                return this.p_PHONEField;
            }
            set {
                this.p_PHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string P_EMAIL {
            get {
                return this.p_EMAILField;
            }
            set {
                this.p_EMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> P_RECORD_LIMIT {
            get {
                return this.p_RECORD_LIMITField;
            }
            set {
                this.p_RECORD_LIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_RECORD_LIMITSpecified {
            get {
                return this.p_RECORD_LIMITFieldSpecified;
            }
            set {
                this.p_RECORD_LIMITFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/hz/soaprovider/plsql/hz_integration_pub/get_contact_" +
        "detail/")]
    public partial class OutputParameters {
        
        private APPSHZ_INTEGRATION_PX3348183X1X7[] x_CONTACT_REC_TBLField;
        
        private string x_RETURN_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("X_CONTACT_REC_TBL_ITEM")]
        public APPSHZ_INTEGRATION_PX3348183X1X7[] X_CONTACT_REC_TBL {
            get {
                return this.x_CONTACT_REC_TBLField;
            }
            set {
                this.x_CONTACT_REC_TBLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_RETURN_STATUS {
            get {
                return this.x_RETURN_STATUSField;
            }
            set {
                this.x_RETURN_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GET_CONTACT_DETAILCompletedEventHandler(object sender, GET_CONTACT_DETAILCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_CONTACT_DETAILCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_CONTACT_DETAILCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputParameters Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputParameters)(this.results[0]));
            }
        }
    }
}
