version: '3'

services:
    test_runner:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/home/python/app
            - ~/.oci:/home/python/.oci
        tty: true
        working_dir: /home/python/app
        command: bash
        ports:
          - 8888:8888
