################################################################################################
#  This file is part of the Oracle Service Cloud Accelerator Reference Integration set published
#  by Oracle Service Cloud under the Universal Permissive License (UPL), Version 1.0 as shown at 
#  http://oss.oracle.com/licenses/upl
#  Copyright (c) 2023, Oracle and/or its affiliates.
################################################################################################
#  Accelerator Package: Incident Text Based Classification
#  link: http://www.oracle.com/technetwork/indexes/samplecode/accelerator-osvc-2525361.html
#  OSvC release: 23A (February 2023) 
#  date: Tue Jan 31 13:02:45 IST 2023
 
#  revision: rnw-23-02-initial
#  SHA1: $Id: be103b91362c7d5244823a8f48edd54e3e6aece3 $
################################################################################################
#  File: docker-compose.yml
################################################################################################

version: '3'

services:
    test_runner:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/home/python/app
            - ~/.oci:/home/python/.oci
        tty: true
        working_dir: /home/python/app
        command: bash
        ports:
          - 8888:8888
