//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MockEBSServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class MockEBSServiceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContractIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IncidentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IncidentOccurredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncidentRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SeverityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContractID {
            get {
                return this.ContractIDField;
            }
            set {
                if ((this.ContractIDField.Equals(value) != true)) {
                    this.ContractIDField = value;
                    this.RaisePropertyChanged("ContractID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IncidentID {
            get {
                return this.IncidentIDField;
            }
            set {
                if ((this.IncidentIDField.Equals(value) != true)) {
                    this.IncidentIDField = value;
                    this.RaisePropertyChanged("IncidentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IncidentOccurredDate {
            get {
                return this.IncidentOccurredDateField;
            }
            set {
                if ((this.IncidentOccurredDateField.Equals(value) != true)) {
                    this.IncidentOccurredDateField = value;
                    this.RaisePropertyChanged("IncidentOccurredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentRef {
            get {
                return this.IncidentRefField;
            }
            set {
                if ((object.ReferenceEquals(this.IncidentRefField, value) != true)) {
                    this.IncidentRefField = value;
                    this.RaisePropertyChanged("IncidentRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestNumber {
            get {
                return this.RequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestNumberField, value) != true)) {
                    this.RequestNumberField = value;
                    this.RaisePropertyChanged("RequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RequestTypeID {
            get {
                return this.RequestTypeIDField;
            }
            set {
                if ((this.RequestTypeIDField.Equals(value) != true)) {
                    this.RequestTypeIDField = value;
                    this.RaisePropertyChanged("RequestTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityField, value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SeverityID {
            get {
                return this.SeverityIDField;
            }
            set {
                if ((this.SeverityIDField.Equals(value) != true)) {
                    this.SeverityIDField = value;
                    this.RaisePropertyChanged("SeverityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SROutputParameters", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class SROutputParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Error_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Request_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Message {
            get {
                return this.Error_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Error_MessageField, value) != true)) {
                    this.Error_MessageField = value;
                    this.RaisePropertyChanged("Error_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Request_ID {
            get {
                return this.Request_IDField;
            }
            set {
                if ((this.Request_IDField.Equals(value) != true)) {
                    this.Request_IDField = value;
                    this.RaisePropertyChanged("Request_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MockEBSContact", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class MockEBSContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MockEBSInteraction", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class MockEBSInteraction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InteractionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SrIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InteractionID {
            get {
                return this.InteractionIDField;
            }
            set {
                if ((this.InteractionIDField.Equals(value) != true)) {
                    this.InteractionIDField = value;
                    this.RaisePropertyChanged("InteractionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SrID {
            get {
                return this.SrIDField;
            }
            set {
                if ((this.SrIDField.Equals(value) != true)) {
                    this.SrIDField = value;
                    this.RaisePropertyChanged("SrID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MockEBSRepairOrder", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class MockEBSRepairOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CustomerProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IncidentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InventoryItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProblemDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RepairLineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepairNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RepairTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ResourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitOfMeasureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalRequired {
            get {
                return this.ApprovalRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalRequiredField, value) != true)) {
                    this.ApprovalRequiredField = value;
                    this.RaisePropertyChanged("ApprovalRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalStatus {
            get {
                return this.ApprovalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalStatusField, value) != true)) {
                    this.ApprovalStatusField = value;
                    this.RaisePropertyChanged("ApprovalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerProductID {
            get {
                return this.CustomerProductIDField;
            }
            set {
                if ((this.CustomerProductIDField.Equals(value) != true)) {
                    this.CustomerProductIDField = value;
                    this.RaisePropertyChanged("CustomerProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IncidentID {
            get {
                return this.IncidentIDField;
            }
            set {
                if ((this.IncidentIDField.Equals(value) != true)) {
                    this.IncidentIDField = value;
                    this.RaisePropertyChanged("IncidentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InventoryItemID {
            get {
                return this.InventoryItemIDField;
            }
            set {
                if ((this.InventoryItemIDField.Equals(value) != true)) {
                    this.InventoryItemIDField = value;
                    this.RaisePropertyChanged("InventoryItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProblemDescription {
            get {
                return this.ProblemDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProblemDescriptionField, value) != true)) {
                    this.ProblemDescriptionField = value;
                    this.RaisePropertyChanged("ProblemDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RepairLineID {
            get {
                return this.RepairLineIDField;
            }
            set {
                if ((this.RepairLineIDField.Equals(value) != true)) {
                    this.RepairLineIDField = value;
                    this.RaisePropertyChanged("RepairLineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepairNumber {
            get {
                return this.RepairNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RepairNumberField, value) != true)) {
                    this.RepairNumberField = value;
                    this.RaisePropertyChanged("RepairNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RepairTypeID {
            get {
                return this.RepairTypeIDField;
            }
            set {
                if ((this.RepairTypeIDField.Equals(value) != true)) {
                    this.RepairTypeIDField = value;
                    this.RaisePropertyChanged("RepairTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResourceID {
            get {
                return this.ResourceIDField;
            }
            set {
                if ((this.ResourceIDField.Equals(value) != true)) {
                    this.ResourceIDField = value;
                    this.RaisePropertyChanged("ResourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitOfMeasure {
            get {
                return this.UnitOfMeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitOfMeasureField, value) != true)) {
                    this.UnitOfMeasureField = value;
                    this.RaisePropertyChanged("UnitOfMeasure");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepairOrderOutputParameters", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class RepairOrderOutputParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Error_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Repair_Line_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Repair_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Message {
            get {
                return this.Error_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Error_MessageField, value) != true)) {
                    this.Error_MessageField = value;
                    this.RaisePropertyChanged("Error_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Repair_Line_ID {
            get {
                return this.Repair_Line_IDField;
            }
            set {
                if ((this.Repair_Line_IDField.Equals(value) != true)) {
                    this.Repair_Line_IDField = value;
                    this.RaisePropertyChanged("Repair_Line_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Repair_Number {
            get {
                return this.Repair_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.Repair_NumberField, value) != true)) {
                    this.Repair_NumberField = value;
                    this.RaisePropertyChanged("Repair_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactOutputParameters", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class ContactOutputParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Error_MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Message {
            get {
                return this.Error_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Error_MessageField, value) != true)) {
                    this.Error_MessageField = value;
                    this.RaisePropertyChanged("Error_Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InteractionOutputParameters", Namespace="http://schemas.datacontract.org/2004/07/EBSMockSvcLib")]
    [System.SerializableAttribute()]
    public partial class InteractionOutputParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Error_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InteractionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Message {
            get {
                return this.Error_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Error_MessageField, value) != true)) {
                    this.Error_MessageField = value;
                    this.RaisePropertyChanged("Error_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InteractionID {
            get {
                return this.InteractionIDField;
            }
            set {
                if ((this.InteractionIDField.Equals(value) != true)) {
                    this.InteractionIDField = value;
                    this.RaisePropertyChanged("InteractionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EBSMockServiceReference.IEBSMockSvc")]
    public interface IEBSMockSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/SaveSR", ReplyAction="http://tempuri.org/IEBSMockSvc/SaveSRResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.SROutputParameters SaveSR(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/LookupSR", ReplyAction="http://tempuri.org/IEBSMockSvc/LookupSRResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest LookupSR(string sr_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssLookupSRBySR_ID", ReplyAction="http://tempuri.org/IEBSMockSvc/wssLookupSRBySR_IDResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest wssLookupSRBySR_ID(string sr_id, string contactPartyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/cxLookupContactDetailsByPartyID", ReplyAction="http://tempuri.org/IEBSMockSvc/cxLookupContactDetailsByPartyIDResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSContact cxLookupContactDetailsByPartyID(string contactPartyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/cxLookupContact", ReplyAction="http://tempuri.org/IEBSMockSvc/cxLookupContactResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSContact[] cxLookupContact(string phone, string email, string fn, string ln);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssLookupSRsByContactPartyID", ReplyAction="http://tempuri.org/IEBSMockSvc/wssLookupSRsByContactPartyIDResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest[] wssLookupSRsByContactPartyID(string contact_id, int maxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssLookupSRsByContactPartyIDNoAuth", ReplyAction="http://tempuri.org/IEBSMockSvc/wssLookupSRsByContactPartyIDNoAuthResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest[] wssLookupSRsByContactPartyIDNoAuth(string contact_id, int maxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssLookupInteractionsBySR_ID", ReplyAction="http://tempuri.org/IEBSMockSvc/wssLookupInteractionsBySR_IDResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSInteraction[] wssLookupInteractionsBySR_ID(string sr_id, string contactPartyID, int maxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/LookupRepairOrder", ReplyAction="http://tempuri.org/IEBSMockSvc/LookupRepairOrderResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSRepairOrder LookupRepairOrder(string repair_line_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssCreateSR", ReplyAction="http://tempuri.org/IEBSMockSvc/wssCreateSRResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.SROutputParameters wssCreateSR(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssUpdateSR", ReplyAction="http://tempuri.org/IEBSMockSvc/wssUpdateSRResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.SROutputParameters wssUpdateSR(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/SaveRepairOrder", ReplyAction="http://tempuri.org/IEBSMockSvc/SaveRepairOrderResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.RepairOrderOutputParameters SaveRepairOrder(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSRepairOrder repair_order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/VerifyInstallation", ReplyAction="http://tempuri.org/IEBSMockSvc/VerifyInstallationResponse")]
        string VerifyInstallation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/LookupAllSR", ReplyAction="http://tempuri.org/IEBSMockSvc/LookupAllSRResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest[] LookupAllSR();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/CreateContact", ReplyAction="http://tempuri.org/IEBSMockSvc/CreateContactResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.ContactOutputParameters CreateContact(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSContact req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEBSMockSvc/wssCreateInteractionsForSR_ID", ReplyAction="http://tempuri.org/IEBSMockSvc/wssCreateInteractionsForSR_IDResponse")]
        Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.InteractionOutputParameters wssCreateInteractionsForSR_ID(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSInteraction req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEBSMockSvcChannel : Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.IEBSMockSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EBSMockSvcClient : System.ServiceModel.ClientBase<Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.IEBSMockSvc>, Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.IEBSMockSvc {
        
        public EBSMockSvcClient() {
        }
        
        public EBSMockSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EBSMockSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EBSMockSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EBSMockSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.SROutputParameters SaveSR(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest req) {
            return base.Channel.SaveSR(req);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest LookupSR(string sr_id) {
            return base.Channel.LookupSR(sr_id);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest wssLookupSRBySR_ID(string sr_id, string contactPartyID) {
            return base.Channel.wssLookupSRBySR_ID(sr_id, contactPartyID);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSContact cxLookupContactDetailsByPartyID(string contactPartyID) {
            return base.Channel.cxLookupContactDetailsByPartyID(contactPartyID);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSContact[] cxLookupContact(string phone, string email, string fn, string ln) {
            return base.Channel.cxLookupContact(phone, email, fn, ln);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest[] wssLookupSRsByContactPartyID(string contact_id, int maxRows) {
            return base.Channel.wssLookupSRsByContactPartyID(contact_id, maxRows);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest[] wssLookupSRsByContactPartyIDNoAuth(string contact_id, int maxRows) {
            return base.Channel.wssLookupSRsByContactPartyIDNoAuth(contact_id, maxRows);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSInteraction[] wssLookupInteractionsBySR_ID(string sr_id, string contactPartyID, int maxRows) {
            return base.Channel.wssLookupInteractionsBySR_ID(sr_id, contactPartyID, maxRows);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSRepairOrder LookupRepairOrder(string repair_line_id) {
            return base.Channel.LookupRepairOrder(repair_line_id);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.SROutputParameters wssCreateSR(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest req) {
            return base.Channel.wssCreateSR(req);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.SROutputParameters wssUpdateSR(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest req) {
            return base.Channel.wssUpdateSR(req);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.RepairOrderOutputParameters SaveRepairOrder(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSRepairOrder repair_order) {
            return base.Channel.SaveRepairOrder(repair_order);
        }
        
        public string VerifyInstallation() {
            return base.Channel.VerifyInstallation();
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSServiceRequest[] LookupAllSR() {
            return base.Channel.LookupAllSR();
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.ContactOutputParameters CreateContact(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSContact req) {
            return base.Channel.CreateContact(req);
        }
        
        public Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.InteractionOutputParameters wssCreateInteractionsForSR_ID(Accelerator.Siebel.ContactSearchAddin.EBSMockServiceReference.MockEBSInteraction req) {
            return base.Channel.wssCreateInteractionsForSR_ID(req);
        }
    }
}
